language: node_js
notifications:
  email:
   - dropbox+travis@ricostacruz.com

scripts:
  - npm test
  # - bash ./support/deploy-to-gh-pages.sh

env:
  global:
    - GH_REF: "github.com/rstacruz/xvsx.git"
    - CI: 1
